services:
  python-app:
    build: .
    container_name: laz_web_processor
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV=production
